version: '3.8'

services:
  llm-api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - USE_REDIS=true
      - REDIS_URL=redis://redis:6379
    depends_on:
      - redis
    volumes:
      - ./models:/app/models  # Cache downloaded models

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"